import {
  type Element,
  type InsertElement,
  type InsertReaction,
  type InsertUser,
  type Reaction,
  type User,
} from "@shared/schema";

export interface IStorage {
  getUser(id: number): Promise<User | undefined>;
  getUserByUsername(username: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;

  getAllElements(): Promise<Element[]>;
  getElementById(id: number): Promise<Element | undefined>;
  getElementBySymbol(symbol: string): Promise<Element | undefined>;
  createElement(element: InsertElement): Promise<Element>;

  getAllReactions(): Promise<Reaction[]>;
  getReactionByReactants(reactants: string[]): Promise<Reaction | undefined>;
  createReaction(reaction: InsertReaction): Promise<Reaction>;
}

export class MemStorage implements IStorage {
  private users: Map<number, User>;
  private elements: Map<number, Element>;
  private reactions: Map<number, Reaction>;
  private currentUserId: number;
  private currentElementId: number;
  private currentReactionId: number;

  constructor() {
    this.users = new Map();
    this.elements = new Map();
    this.reactions = new Map();
    this.currentUserId = 1;
    this.currentElementId = 1;
    this.currentReactionId = 1;

    // Initialize with basic elements and reactions
    this.initializeData().catch(console.error);
  }

  private async initializeData() {
    // Initialize all 118 elements of the periodic table
    const elementData = [
      // Period 1
      {
        symbol: "H",
        name: "Hydrogen",
        atomicNumber: 1,
        atomicMass: 1.008,
        category: "nonmetal",
        period: 1,
        group: 1,
        electronConfiguration: "1s¹",
        meltingPoint: "-259.1°C",
        boilingPoint: "-252.9°C",
        uses: "Fuel cells, rocket fuel, industrial processes",
        fact: "Hydrogen is the most abundant element in the universe, making up about 75% of all matter.",
      },
      {
        symbol: "He",
        name: "Helium",
        atomicNumber: 2,
        atomicMass: 4.003,
        category: "noble-gas",
        period: 1,
        group: 18,
        electronConfiguration: "1s²",
        meltingPoint: "-272.2°C",
        boilingPoint: "-268.9°C",
        uses: "Balloons, welding, medical equipment",
        fact: "Helium is the second most abundant element in the universe but very rare on Earth.",
      },

      // Period 2
      {
        symbol: "Li",
        name: "Lithium",
        atomicNumber: 3,
        atomicMass: 6.94,
        category: "alkali-metal",
        period: 2,
        group: 1,
        electronConfiguration: "[He] 2s¹",
        meltingPoint: "180.5°C",
        boilingPoint: "1342°C",
        uses: "Batteries, ceramics, mental health medication",
        fact: "Lithium is the lightest metal and can cut with a knife.",
      },
      {
        symbol: "Be",
        name: "Beryllium",
        atomicNumber: 4,
        atomicMass: 9.012,
        category: "alkaline-earth",
        period: 2,
        group: 2,
        electronConfiguration: "[He] 2s²",
        meltingPoint: "1287°C",
        boilingPoint: "2468°C",
        uses: "Aerospace alloys, nuclear reactors, X-ray equipment",
        fact: "Beryllium is transparent to X-rays and is used in X-ray tube windows.",
      },
      {
        symbol: "B",
        name: "Boron",
        atomicNumber: 5,
        atomicMass: 10.81,
        category: "metalloid",
        period: 2,
        group: 13,
        electronConfiguration: "[He] 2s² 2p¹",
        meltingPoint: "2076°C",
        boilingPoint: "4000°C",
        uses: "Glass, detergents, semiconductors",
        fact: "Boron is essential for plant growth and is used in high-strength glass.",
      },
      {
        symbol: "C",
        name: "Carbon",
        atomicNumber: 6,
        atomicMass: 12.01,
        category: "nonmetal",
        period: 2,
        group: 14,
        electronConfiguration: "[He] 2s² 2p²",
        meltingPoint: "3550°C",
        boilingPoint: "4027°C",
        uses: "Diamond, graphite, organic compounds, steel",
        fact: "Carbon can form more compounds than any other element except hydrogen.",
      },
      {
        symbol: "N",
        name: "Nitrogen",
        atomicNumber: 7,
        atomicMass: 14.01,
        category: "nonmetal",
        period: 2,
        group: 15,
        electronConfiguration: "[He] 2s² 2p³",
        meltingPoint: "-210.0°C",
        boilingPoint: "-195.8°C",
        uses: "Fertilizers, explosives, food preservation",
        fact: "Nitrogen makes up about 78% of Earth's atmosphere.",
      },
      {
        symbol: "O",
        name: "Oxygen",
        atomicNumber: 8,
        atomicMass: 15.99,
        category: "nonmetal",
        period: 2,
        group: 16,
        electronConfiguration: "[He] 2s² 2p⁴",
        meltingPoint: "-218.3°C",
        boilingPoint: "-182.9°C",
        uses: "Breathing, combustion, water, medical oxygen",
        fact: "Oxygen is the most abundant element in Earth's crust.",
      },
      {
        symbol: "F",
        name: "Fluorine",
        atomicNumber: 9,
        atomicMass: 18.99,
        category: "halogen",
        period: 2,
        group: 17,
        electronConfiguration: "[He] 2s² 2p⁵",
        meltingPoint: "-219.7°C",
        boilingPoint: "-188.1°C",
        uses: "Toothpaste, Teflon, refrigerants",
        fact: "Fluorine is the most electronegative element and highly reactive.",
      },
      {
        symbol: "Ne",
        name: "Neon",
        atomicNumber: 10,
        atomicMass: 20.18,
        category: "noble-gas",
        period: 2,
        group: 18,
        electronConfiguration: "[He] 2s² 2p⁶",
        meltingPoint: "-248.6°C",
        boilingPoint: "-246.1°C",
        uses: "Neon signs, lasers, cryogenics",
        fact: "Neon gives off a distinctive red-orange glow when used in gas-discharge tubes.",
      },

      // Period 3
      {
        symbol: "Na",
        name: "Sodium",
        atomicNumber: 11,
        atomicMass: 22.99,
        category: "alkali-metal",
        period: 3,
        group: 1,
        electronConfiguration: "[Ne] 3s¹",
        meltingPoint: "97.8°C",
        boilingPoint: "883°C",
        uses: "Table salt, soap, street lights",
        fact: "Sodium is so reactive that it must be stored under oil to prevent reaction with air.",
      },
      {
        symbol: "Mg",
        name: "Magnesium",
        atomicNumber: 12,
        atomicMass: 24.31,
        category: "alkaline-earth",
        period: 3,
        group: 2,
        electronConfiguration: "[Ne] 3s²",
        meltingPoint: "650°C",
        boilingPoint: "1090°C",
        uses: "Lightweight alloys, fireworks, photography",
        fact: "Magnesium burns with a brilliant white flame and is used in fireworks and photography.",
      },
      {
        symbol: "Al",
        name: "Aluminum",
        atomicNumber: 13,
        atomicMass: 26.98,
        category: "post-transition",
        period: 3,
        group: 13,
        electronConfiguration: "[Ne] 3s² 3p¹",
        meltingPoint: "660.3°C",
        boilingPoint: "2519°C",
        uses: "Cans, aircraft, building materials",
        fact: "Aluminum is the most abundant metal in Earth's crust but was once more valuable than gold.",
      },
      {
        symbol: "Si",
        name: "Silicon",
        atomicNumber: 14,
        atomicMass: 28.09,
        category: "metalloid",
        period: 3,
        group: 14,
        electronConfiguration: "[Ne] 3s² 3p²",
        meltingPoint: "1414°C",
        boilingPoint: "3265°C",
        uses: "Computer chips, glass, solar panels",
        fact: "Silicon is the second most abundant element in Earth's crust and is essential for computer technology.",
      },
      {
        symbol: "P",
        name: "Phosphorus",
        atomicNumber: 15,
        atomicMass: 30.97,
        category: "nonmetal",
        period: 3,
        group: 15,
        electronConfiguration: "[Ne] 3s² 3p³",
        meltingPoint: "44.2°C",
        boilingPoint: "280.5°C",
        uses: "Fertilizers, matches, DNA, bones",
        fact: "Phosphorus glows in the dark and is essential for all life on Earth.",
      },
      {
        symbol: "S",
        name: "Sulfur",
        atomicNumber: 16,
        atomicMass: 32.07,
        category: "nonmetal",
        period: 3,
        group: 16,
        electronConfiguration: "[Ne] 3s² 3p⁴",
        meltingPoint: "115.2°C",
        boilingPoint: "444.6°C",
        uses: "Rubber, gunpowder, fertilizers",
        fact: "Sulfur has been known since ancient times and is mentioned in religious texts.",
      },
      {
        symbol: "Cl",
        name: "Chlorine",
        atomicNumber: 17,
        atomicMass: 35.45,
        category: "halogen",
        period: 3,
        group: 17,
        electronConfiguration: "[Ne] 3s² 3p⁵",
        meltingPoint: "-101.5°C",
        boilingPoint: "-34.0°C",
        uses: "Water purification, bleach, PVC plastic",
        fact: "Chlorine is essential for swimming pool sanitation and water treatment.",
      },
      {
        symbol: "Ar",
        name: "Argon",
        atomicNumber: 18,
        atomicMass: 39.95,
        category: "noble-gas",
        period: 3,
        group: 18,
        electronConfiguration: "[Ne] 3s² 3p⁶",
        meltingPoint: "-189.3°C",
        boilingPoint: "-185.8°C",
        uses: "Welding, light bulbs, wine preservation",
        fact: "Argon makes up about 1% of Earth's atmosphere and is used to protect materials from oxidation.",
      },

      // Period 4
      {
        symbol: "K",
        name: "Potassium",
        atomicNumber: 19,
        atomicMass: 39.1,
        category: "alkali-metal",
        period: 4,
        group: 1,
        electronConfiguration: "[Ar] 4s¹",
        meltingPoint: "63.4°C",
        boilingPoint: "759°C",
        uses: "Fertilizers, bananas, nerve function",
        fact: "Potassium is essential for life and is found in high concentrations in bananas.",
      },
      {
        symbol: "Ca",
        name: "Calcium",
        atomicNumber: 20,
        atomicMass: 40.08,
        category: "alkaline-earth",
        period: 4,
        group: 2,
        electronConfiguration: "[Ar] 4s²",
        meltingPoint: "842°C",
        boilingPoint: "1484°C",
        uses: "Bones, teeth, concrete, milk",
        fact: "Calcium is the fifth most abundant element in Earth's crust and is essential for bone health.",
      },
      {
        symbol: "Sc",
        name: "Scandium",
        atomicNumber: 21,
        atomicMass: 44.96,
        category: "transition-metal",
        period: 4,
        group: 3,
        electronConfiguration: "[Ar] 3d¹ 4s²",
        meltingPoint: "1541°C",
        boilingPoint: "2836°C",
        uses: "Aerospace components, sports equipment",
        fact: "Scandium is one of the rarest earth elements and makes aluminum alloys stronger.",
      },
      {
        symbol: "Ti",
        name: "Titanium",
        atomicNumber: 22,
        atomicMass: 47.87,
        category: "transition-metal",
        period: 4,
        group: 4,
        electronConfiguration: "[Ar] 3d² 4s²",
        meltingPoint: "1668°C",
        boilingPoint: "3287°C",
        uses: "Aircraft, medical implants, jewelry",
        fact: "Titanium is as strong as steel but 45% lighter and highly corrosion resistant.",
      },
      {
        symbol: "V",
        name: "Vanadium",
        atomicNumber: 23,
        atomicMass: 50.94,
        category: "transition-metal",
        period: 4,
        group: 5,
        electronConfiguration: "[Ar] 3d³ 4s²",
        meltingPoint: "1910°C",
        boilingPoint: "3407°C",
        uses: "Steel alloys, catalysts",
        fact: "Vanadium improves steel strength and is used in tools and springs.",
      },
      {
        symbol: "Cr",
        name: "Chromium",
        atomicNumber: 24,
        atomicMass: 52.0,
        category: "transition-metal",
        period: 4,
        group: 6,
        electronConfiguration: "[Ar] 3d⁵ 4s¹",
        meltingPoint: "1907°C",
        boilingPoint: "2671°C",
        uses: "Stainless steel, chrome plating",
        fact: "Chromium gives stainless steel its corrosion resistance and shiny appearance.",
      },
      {
        symbol: "Mn",
        name: "Manganese",
        atomicNumber: 25,
        atomicMass: 54.94,
        category: "transition-metal",
        period: 4,
        group: 7,
        electronConfiguration: "[Ar] 3d⁵ 4s²",
        meltingPoint: "1246°C",
        boilingPoint: "2061°C",
        uses: "Steel production, batteries, fertilizers",
        fact: "Manganese is essential for steel production and removes oxygen and sulfur impurities.",
      },
      {
        symbol: "Fe",
        name: "Iron",
        atomicNumber: 26,
        atomicMass: 55.85,
        category: "transition-metal",
        period: 4,
        group: 8,
        electronConfiguration: "[Ar] 3d⁶ 4s²",
        meltingPoint: "1538°C",
        boilingPoint: "2861°C",
        uses: "Steel, construction, red blood cells",
        fact: "Iron is the most abundant element on Earth by mass and is essential for oxygen transport in blood.",
      },
      {
        symbol: "Co",
        name: "Cobalt",
        atomicNumber: 27,
        atomicMass: 58.93,
        category: "transition-metal",
        period: 4,
        group: 9,
        electronConfiguration: "[Ar] 3d⁷ 4s²",
        meltingPoint: "1495°C",
        boilingPoint: "2927°C",
        uses: "Magnets, batteries, blue pigments",
        fact: "Cobalt creates the blue color in glass and ceramics and is used in rechargeable batteries.",
      },
      {
        symbol: "Ni",
        name: "Nickel",
        atomicNumber: 28,
        atomicMass: 58.69,
        category: "transition-metal",
        period: 4,
        group: 10,
        electronConfiguration: "[Ar] 3d⁸ 4s²",
        meltingPoint: "1455°C",
        boilingPoint: "2913°C",
        uses: "Stainless steel, coins, batteries",
        fact: "Nickel is used in coins and gives stainless steel additional corrosion resistance.",
      },
      {
        symbol: "Cu",
        name: "Copper",
        atomicNumber: 29,
        atomicMass: 63.55,
        category: "transition-metal",
        period: 4,
        group: 11,
        electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
        meltingPoint: "1085°C",
        boilingPoint: "2562°C",
        uses: "Electrical wiring, plumbing, coins",
        fact: "Copper is one of the few metals that occurs naturally in its metallic form.",
      },
      {
        symbol: "Zn",
        name: "Zinc",
        atomicNumber: 30,
        atomicMass: 65.38,
        category: "transition-metal",
        period: 4,
        group: 12,
        electronConfiguration: "[Ar] 3d¹⁰ 4s²",
        meltingPoint: "419.5°C",
        boilingPoint: "907°C",
        uses: "Galvanizing, batteries, dietary supplements",
        fact: "Zinc is essential for human health and is found in many foods.",
      },
      {
        symbol: "Ga",
        name: "Gallium",
        atomicNumber: 31,
        atomicMass: 69.72,
        category: "post-transition",
        period: 4,
        group: 13,
        electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
        meltingPoint: "29.8°C",
        boilingPoint: "2204°C",
        uses: "Semiconductors, LEDs, thermometers",
        fact: "Gallium melts in your hand at body temperature and is used in advanced electronics.",
      },
      {
        symbol: "Ge",
        name: "Germanium",
        atomicNumber: 32,
        atomicMass: 72.63,
        category: "metalloid",
        period: 4,
        group: 14,
        electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
        meltingPoint: "938.3°C",
        boilingPoint: "2833°C",
        uses: "Semiconductors, fiber optics, infrared optics",
        fact: "Germanium was one of the first semiconductor materials and predicted by Mendeleev before its discovery.",
      },
      {
        symbol: "As",
        name: "Arsenic",
        atomicNumber: 33,
        atomicMass: 74.92,
        category: "metalloid",
        period: 4,
        group: 15,
        electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
        meltingPoint: "817°C",
        boilingPoint: "614°C",
        uses: "Semiconductors, wood preservatives, pesticides",
        fact: "Arsenic is toxic but has important uses in electronics and was historically used in medicine.",
      },
      {
        symbol: "Se",
        name: "Selenium",
        atomicNumber: 34,
        atomicMass: 78.97,
        category: "nonmetal",
        period: 4,
        group: 16,
        electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
        meltingPoint: "221°C",
        boilingPoint: "685°C",
        uses: "Electronics, glass, nutrition supplements",
        fact: "Selenium is essential for human health and gives photoconductivity to electronic devices.",
      },
      {
        symbol: "Br",
        name: "Bromine",
        atomicNumber: 35,
        atomicMass: 79.9,
        category: "halogen",
        period: 4,
        group: 17,
        electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
        meltingPoint: "-7.3°C",
        boilingPoint: "58.8°C",
        uses: "Flame retardants, photography, water treatment",
        fact: "Bromine is one of only two elements that are liquid at room temperature.",
      },
      {
        symbol: "Kr",
        name: "Krypton",
        atomicNumber: 36,
        atomicMass: 83.8,
        category: "noble-gas",
        period: 4,
        group: 18,
        electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
        meltingPoint: "-157.4°C",
        boilingPoint: "-153.2°C",
        uses: "Photography, lasers, energy-efficient windows",
        fact: "Krypton is used in high-performance windows and produces a bright white light in photography.",
      },

      // Period 5
      {
        symbol: "Rb",
        name: "Rubidium",
        atomicNumber: 37,
        atomicMass: 85.47,
        category: "alkali-metal",
        period: 5,
        group: 1,
        electronConfiguration: "[Kr] 5s¹",
        meltingPoint: "39.3°C",
        boilingPoint: "688°C",
        uses: "Research, atomic clocks, specialty glass",
        fact: "Rubidium is so reactive it ignites spontaneously in air and is used in atomic clocks.",
      },
      {
        symbol: "Sr",
        name: "Strontium",
        atomicNumber: 38,
        atomicMass: 87.62,
        category: "alkaline-earth",
        period: 5,
        group: 2,
        electronConfiguration: "[Kr] 5s²",
        meltingPoint: "777°C",
        boilingPoint: "1382°C",
        uses: "Fireworks, flares, bone treatment",
        fact: "Strontium gives fireworks and flares their bright red color.",
      },
      {
        symbol: "Y",
        name: "Yttrium",
        atomicNumber: 39,
        atomicMass: 88.91,
        category: "transition-metal",
        period: 5,
        group: 3,
        electronConfiguration: "[Kr] 4d¹ 5s²",
        meltingPoint: "1526°C",
        boilingPoint: "3345°C",
        uses: "Lasers, superconductors, cancer treatment",
        fact: "Yttrium is used in medical treatments and gives red color to TV screens.",
      },
      {
        symbol: "Zr",
        name: "Zirconium",
        atomicNumber: 40,
        atomicMass: 91.22,
        category: "transition-metal",
        period: 5,
        group: 4,
        electronConfiguration: "[Kr] 4d² 5s²",
        meltingPoint: "1855°C",
        boilingPoint: "4409°C",
        uses: "Nuclear reactors, ceramics, jewelry",
        fact: "Zirconium is extremely corrosion-resistant and used in nuclear reactor cores.",
      },
      {
        symbol: "Nb",
        name: "Niobium",
        atomicNumber: 41,
        atomicMass: 92.91,
        category: "transition-metal",
        period: 5,
        group: 5,
        electronConfiguration: "[Kr] 4d⁴ 5s¹",
        meltingPoint: "2477°C",
        boilingPoint: "4744°C",
        uses: "Superconducting magnets, steel alloys",
        fact: "Niobium becomes superconducting at low temperatures and is used in MRI machines.",
      },
      {
        symbol: "Mo",
        name: "Molybdenum",
        atomicNumber: 42,
        atomicMass: 95.95,
        category: "transition-metal",
        period: 5,
        group: 6,
        electronConfiguration: "[Kr] 4d⁵ 5s¹",
        meltingPoint: "2623°C",
        boilingPoint: "4639°C",
        uses: "Steel alloys, catalysts, lubricants",
        fact: "Molybdenum has one of the highest melting points of all elements and strengthens steel.",
      },
      {
        symbol: "Tc",
        name: "Technetium",
        atomicNumber: 43,
        atomicMass: 98,
        category: "transition-metal",
        period: 5,
        group: 7,
        electronConfiguration: "[Kr] 4d⁵ 5s²",
        meltingPoint: "2157°C",
        boilingPoint: "4265°C",
        uses: "Medical imaging, nuclear medicine",
        fact: "Technetium was the first artificially produced element and is used in medical scans.",
      },
      {
        symbol: "Ru",
        name: "Ruthenium",
        atomicNumber: 44,
        atomicMass: 101.07,
        category: "transition-metal",
        period: 5,
        group: 8,
        electronConfiguration: "[Kr] 4d⁷ 5s¹",
        meltingPoint: "2334°C",
        boilingPoint: "4150°C",
        uses: "Electronics, jewelry, catalysts",
        fact: "Ruthenium is one of the rarest platinum group metals and extremely valuable.",
      },
      {
        symbol: "Rh",
        name: "Rhodium",
        atomicNumber: 45,
        atomicMass: 102.91,
        category: "transition-metal",
        period: 5,
        group: 9,
        electronConfiguration: "[Kr] 4d⁸ 5s¹",
        meltingPoint: "1964°C",
        boilingPoint: "3695°C",
        uses: "Catalytic converters, jewelry, mirrors",
        fact: "Rhodium is one of the most expensive precious metals and used in car catalytic converters.",
      },
      {
        symbol: "Pd",
        name: "Palladium",
        atomicNumber: 46,
        atomicMass: 106.42,
        category: "transition-metal",
        period: 5,
        group: 10,
        electronConfiguration: "[Kr] 4d¹⁰",
        meltingPoint: "1555°C",
        boilingPoint: "2963°C",
        uses: "Catalytic converters, jewelry, electronics",
        fact: "Palladium can absorb hydrogen up to 900 times its own volume.",
      },
      {
        symbol: "Ag",
        name: "Silver",
        atomicNumber: 47,
        atomicMass: 107.87,
        category: "transition-metal",
        period: 5,
        group: 11,
        electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
        meltingPoint: "961.8°C",
        boilingPoint: "2162°C",
        uses: "Jewelry, photography, electronics",
        fact: "Silver has the highest electrical conductivity of any element.",
      },
      {
        symbol: "Cd",
        name: "Cadmium",
        atomicNumber: 48,
        atomicMass: 112.41,
        category: "transition-metal",
        period: 5,
        group: 12,
        electronConfiguration: "[Kr] 4d¹⁰ 5s²",
        meltingPoint: "321.1°C",
        boilingPoint: "767°C",
        uses: "Batteries, pigments, coatings",
        fact: "Cadmium is toxic but useful in rechargeable batteries and gives bright colors to paints.",
      },
      {
        symbol: "In",
        name: "Indium",
        atomicNumber: 49,
        atomicMass: 114.82,
        category: "post-transition",
        period: 5,
        group: 13,
        electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
        meltingPoint: "156.6°C",
        boilingPoint: "2072°C",
        uses: "Touchscreens, semiconductors, solders",
        fact: "Indium is used to make touchscreens work and creates transparent conducting coatings.",
      },
      {
        symbol: "Sn",
        name: "Tin",
        atomicNumber: 50,
        atomicMass: 118.71,
        category: "post-transition",
        period: 5,
        group: 14,
        electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
        meltingPoint: "231.9°C",
        boilingPoint: "2602°C",
        uses: "Cans, solders, alloys",
        fact: "Tin has been used for thousands of years and prevents iron from rusting in tin cans.",
      },
      {
        symbol: "Sb",
        name: "Antimony",
        atomicNumber: 51,
        atomicMass: 121.76,
        category: "metalloid",
        period: 5,
        group: 15,
        electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
        meltingPoint: "630.6°C",
        boilingPoint: "1587°C",
        uses: "Flame retardants, semiconductors, alloys",
        fact: "Antimony has been used since ancient times and makes materials flame-resistant.",
      },
      {
        symbol: "Te",
        name: "Tellurium",
        atomicNumber: 52,
        atomicMass: 127.6,
        category: "metalloid",
        period: 5,
        group: 16,
        electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
        meltingPoint: "449.5°C",
        boilingPoint: "988°C",
        uses: "Solar panels, thermoelectrics, alloys",
        fact: "Tellurium is one of the rarest stable elements and used in advanced solar panels.",
      },
      {
        symbol: "I",
        name: "Iodine",
        atomicNumber: 53,
        atomicMass: 126.9,
        category: "halogen",
        period: 5,
        group: 17,
        electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
        meltingPoint: "113.7°C",
        boilingPoint: "184.3°C",
        uses: "Disinfectants, medical imaging, nutrition",
        fact: "Iodine is essential for thyroid function and creates purple vapor when heated.",
      },
      {
        symbol: "Xe",
        name: "Xenon",
        atomicNumber: 54,
        atomicMass: 131.29,
        category: "noble-gas",
        period: 5,
        group: 18,
        electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
        meltingPoint: "-111.8°C",
        boilingPoint: "-108.1°C",
        uses: "Light bulbs, anesthetics, ion propulsion",
        fact: "Xenon produces an extremely bright light and is used in car headlights and space propulsion.",
      },

      // Period 6
      {
        symbol: "Cs",
        name: "Cesium",
        atomicNumber: 55,
        atomicMass: 132.91,
        category: "alkali-metal",
        period: 6,
        group: 1,
        electronConfiguration: "[Xe] 6s¹",
        meltingPoint: "28.4°C",
        boilingPoint: "671°C",
        uses: "Atomic clocks, drilling fluids, photoelectric cells",
        fact: "Cesium is used to define the second in atomic clocks and is extremely reactive.",
      },
      {
        symbol: "Ba",
        name: "Barium",
        atomicNumber: 56,
        atomicMass: 137.33,
        category: "alkaline-earth",
        period: 6,
        group: 2,
        electronConfiguration: "[Xe] 6s²",
        meltingPoint: "727°C",
        boilingPoint: "1870°C",
        uses: "Medical imaging, fireworks, drilling mud",
        fact: "Barium compounds are used in medical X-rays and give fireworks a green color.",
      },

      // Lanthanides (Period 6)
      {
        symbol: "La",
        name: "Lanthanum",
        atomicNumber: 57,
        atomicMass: 138.91,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 5d¹ 6s²",
        meltingPoint: "920°C",
        boilingPoint: "3464°C",
        uses: "Camera lenses, lighting, batteries",
        fact: "Lanthanum improves the refractive index of glass and is used in expensive camera lenses.",
      },
      {
        symbol: "Ce",
        name: "Cerium",
        atomicNumber: 58,
        atomicMass: 140.12,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
        meltingPoint: "798°C",
        boilingPoint: "3443°C",
        uses: "Catalytic converters, lighter flints, glass polishing",
        fact: "Cerium is the most abundant rare earth element and used in catalytic converters.",
      },
      {
        symbol: "Pr",
        name: "Praseodymium",
        atomicNumber: 59,
        atomicMass: 140.91,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f³ 6s²",
        meltingPoint: "931°C",
        boilingPoint: "3520°C",
        uses: "Magnets, lasers, aircraft engines",
        fact: "Praseodymium creates a distinctive green color and is used in high-strength magnets.",
      },
      {
        symbol: "Nd",
        name: "Neodymium",
        atomicNumber: 60,
        atomicMass: 144.24,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f⁴ 6s²",
        meltingPoint: "1021°C",
        boilingPoint: "3074°C",
        uses: "Permanent magnets, lasers, electric motors",
        fact: "Neodymium magnets are the strongest permanent magnets and used in electric vehicles.",
      },
      {
        symbol: "Pm",
        name: "Promethium",
        atomicNumber: 61,
        atomicMass: 145,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f⁵ 6s²",
        meltingPoint: "1042°C",
        boilingPoint: "3000°C",
        uses: "Nuclear batteries, research",
        fact: "Promethium is radioactive and was the last rare earth element to be discovered.",
      },
      {
        symbol: "Sm",
        name: "Samarium",
        atomicNumber: 62,
        atomicMass: 150.36,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f⁶ 6s²",
        meltingPoint: "1074°C",
        boilingPoint: "1794°C",
        uses: "Magnets, nuclear reactors, cancer treatment",
        fact: "Samarium-cobalt magnets work at high temperatures and are used in aerospace applications.",
      },
      {
        symbol: "Eu",
        name: "Europium",
        atomicNumber: 63,
        atomicMass: 151.96,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f⁷ 6s²",
        meltingPoint: "822°C",
        boilingPoint: "1529°C",
        uses: "TV screens, anti-counterfeiting, lasers",
        fact: "Europium produces red and blue phosphors in TV screens and is used in euro banknotes.",
      },
      {
        symbol: "Gd",
        name: "Gadolinium",
        atomicNumber: 64,
        atomicMass: 157.25,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
        meltingPoint: "1313°C",
        boilingPoint: "3273°C",
        uses: "MRI contrast agents, neutron capture, magnets",
        fact: "Gadolinium is used in MRI scans to improve image contrast and has unique magnetic properties.",
      },
      {
        symbol: "Tb",
        name: "Terbium",
        atomicNumber: 65,
        atomicMass: 158.93,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f⁹ 6s²",
        meltingPoint: "1356°C",
        boilingPoint: "3230°C",
        uses: "Green phosphors, solid-state devices, fuel cells",
        fact: "Terbium produces green color in fluorescent lamps and is used in advanced displays.",
      },
      {
        symbol: "Dy",
        name: "Dysprosium",
        atomicNumber: 66,
        atomicMass: 162.5,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f¹⁰ 6s²",
        meltingPoint: "1412°C",
        boilingPoint: "2567°C",
        uses: "Magnets, lasers, nuclear reactors",
        fact: "Dysprosium helps magnets work at high temperatures and is critical for wind turbines.",
      },
      {
        symbol: "Ho",
        name: "Holmium",
        atomicNumber: 67,
        atomicMass: 164.93,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f¹¹ 6s²",
        meltingPoint: "1474°C",
        boilingPoint: "2700°C",
        uses: "Lasers, magnetic flux concentrators",
        fact: "Holmium has the highest magnetic permeability of any element and is used in medical lasers.",
      },
      {
        symbol: "Er",
        name: "Erbium",
        atomicNumber: 68,
        atomicMass: 167.26,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f¹² 6s²",
        meltingPoint: "1529°C",
        boilingPoint: "2868°C",
        uses: "Fiber optics, lasers, nuclear technology",
        fact: "Erbium amplifies light signals in fiber optic communications and gives pink color to glass.",
      },
      {
        symbol: "Tm",
        name: "Thulium",
        atomicNumber: 69,
        atomicMass: 168.93,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f¹³ 6s²",
        meltingPoint: "1545°C",
        boilingPoint: "1950°C",
        uses: "Medical X-rays, lasers, research",
        fact: "Thulium is the least abundant rare earth element and used in portable medical X-ray devices.",
      },
      {
        symbol: "Yb",
        name: "Ytterbium",
        atomicNumber: 70,
        atomicMass: 173.05,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f¹⁴ 6s²",
        meltingPoint: "824°C",
        boilingPoint: "1196°C",
        uses: "Lasers, atomic clocks, steel improvement",
        fact: "Ytterbium is used in the most precise atomic clocks and high-power fiber lasers.",
      },
      {
        symbol: "Lu",
        name: "Lutetium",
        atomicNumber: 71,
        atomicMass: 174.97,
        category: "lanthanide",
        period: 6,
        group: null,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
        meltingPoint: "1663°C",
        boilingPoint: "3402°C",
        uses: "Medical imaging, research, catalysts",
        fact: "Lutetium is the rarest and most expensive rare earth element.",
      },

      // Transition metals continued (Period 6)
      {
        symbol: "Hf",
        name: "Hafnium",
        atomicNumber: 72,
        atomicMass: 178.49,
        category: "transition-metal",
        period: 6,
        group: 4,
        electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
        meltingPoint: "2233°C",
        boilingPoint: "4603°C",
        uses: "Nuclear reactors, superalloys, electronics",
        fact: "Hafnium absorbs neutrons and is used in nuclear reactor control rods.",
      },
      {
        symbol: "Ta",
        name: "Tantalum",
        atomicNumber: 73,
        atomicMass: 180.95,
        category: "transition-metal",
        period: 6,
        group: 5,
        electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
        meltingPoint: "3017°C",
        boilingPoint: "5458°C",
        uses: "Electronics, medical implants, superalloys",
        fact: "Tantalum is extremely corrosion-resistant and used in smartphone capacitors.",
      },
      {
        symbol: "W",
        name: "Tungsten",
        atomicNumber: 74,
        atomicMass: 183.84,
        category: "transition-metal",
        period: 6,
        group: 6,
        electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
        meltingPoint: "3414°C",
        boilingPoint: "5555°C",
        uses: "Light bulb filaments, cutting tools, electronics",
        fact: "Tungsten has the highest melting point of any metal and is used in incandescent bulbs.",
      },
      {
        symbol: "Re",
        name: "Rhenium",
        atomicNumber: 75,
        atomicMass: 186.21,
        category: "transition-metal",
        period: 6,
        group: 7,
        electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
        meltingPoint: "3186°C",
        boilingPoint: "5596°C",
        uses: "Jet engines, catalysts, thermocouples",
        fact: "Rhenium is one of the rarest elements and used in high-temperature jet engine components.",
      },
      {
        symbol: "Os",
        name: "Osmium",
        atomicNumber: 76,
        atomicMass: 190.23,
        category: "transition-metal",
        period: 6,
        group: 8,
        electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
        meltingPoint: "3033°C",
        boilingPoint: "5012°C",
        uses: "Fountain pen tips, electrical contacts, catalysts",
        fact: "Osmium is the densest naturally occurring element and extremely rare.",
      },
      {
        symbol: "Ir",
        name: "Iridium",
        atomicNumber: 77,
        atomicMass: 192.22,
        category: "transition-metal",
        period: 6,
        group: 9,
        electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
        meltingPoint: "2466°C",
        boilingPoint: "4428°C",
        uses: "Spark plugs, crucibles, jewelry",
        fact: "Iridium is extremely corrosion-resistant and was used to define the meter standard.",
      },
      {
        symbol: "Pt",
        name: "Platinum",
        atomicNumber: 78,
        atomicMass: 195.08,
        category: "transition-metal",
        period: 6,
        group: 10,
        electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
        meltingPoint: "1768.3°C",
        boilingPoint: "3825°C",
        uses: "Catalytic converters, jewelry, medical equipment",
        fact: "Platinum is 30 times rarer than gold and used in life-saving medical devices.",
      },
      {
        symbol: "Au",
        name: "Gold",
        atomicNumber: 79,
        atomicMass: 196.97,
        category: "transition-metal",
        period: 6,
        group: 11,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
        meltingPoint: "1064.2°C",
        boilingPoint: "2856°C",
        uses: "Jewelry, electronics, currency",
        fact: "Gold is so unreactive that it can be found in nature in its pure form.",
      },
      {
        symbol: "Hg",
        name: "Mercury",
        atomicNumber: 80,
        atomicMass: 200.59,
        category: "transition-metal",
        period: 6,
        group: 12,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
        meltingPoint: "-38.8°C",
        boilingPoint: "356.7°C",
        uses: "Thermometers, fluorescent lamps, switches",
        fact: "Mercury is the only metal that is liquid at room temperature.",
      },
      {
        symbol: "Tl",
        name: "Thallium",
        atomicNumber: 81,
        atomicMass: 204.38,
        category: "post-transition",
        period: 6,
        group: 13,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
        meltingPoint: "304°C",
        boilingPoint: "1473°C",
        uses: "Electronics, optics, medical imaging",
        fact: "Thallium is highly toxic but used in specialized electronic components and medical scans.",
      },
      {
        symbol: "Pb",
        name: "Lead",
        atomicNumber: 82,
        atomicMass: 207.2,
        category: "post-transition",
        period: 6,
        group: 14,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
        meltingPoint: "327.5°C",
        boilingPoint: "1749°C",
        uses: "Batteries, radiation shielding, weights",
        fact: "Lead has been used for thousands of years and provides excellent radiation protection.",
      },
      {
        symbol: "Bi",
        name: "Bismuth",
        atomicNumber: 83,
        atomicMass: 208.98,
        category: "post-transition",
        period: 6,
        group: 15,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
        meltingPoint: "271.4°C",
        boilingPoint: "1564°C",
        uses: "Cosmetics, medicine, low-melting alloys",
        fact: "Bismuth creates beautiful rainbow-colored crystals and is used in stomach medicines.",
      },
      {
        symbol: "Po",
        name: "Polonium",
        atomicNumber: 84,
        atomicMass: 209,
        category: "post-transition",
        period: 6,
        group: 16,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
        meltingPoint: "254°C",
        boilingPoint: "962°C",
        uses: "Anti-static devices, nuclear research",
        fact: "Polonium was discovered by Marie Curie and is extremely radioactive.",
      },
      {
        symbol: "At",
        name: "Astatine",
        atomicNumber: 85,
        atomicMass: 210,
        category: "halogen",
        period: 6,
        group: 17,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
        meltingPoint: "302°C",
        boilingPoint: "337°C",
        uses: "Cancer treatment, research",
        fact: "Astatine is the rarest naturally occurring element and used in targeted cancer therapy.",
      },
      {
        symbol: "Rn",
        name: "Radon",
        atomicNumber: 86,
        atomicMass: 222,
        category: "noble-gas",
        period: 6,
        group: 18,
        electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
        meltingPoint: "-71°C",
        boilingPoint: "-62°C",
        uses: "Cancer treatment, earthquake prediction",
        fact: "Radon is radioactive and can accumulate in buildings, posing health risks.",
      },

      // Period 7
      {
        symbol: "Fr",
        name: "Francium",
        atomicNumber: 87,
        atomicMass: 223,
        category: "alkali-metal",
        period: 7,
        group: 1,
        electronConfiguration: "[Rn] 7s¹",
        meltingPoint: "27°C",
        boilingPoint: "677°C",
        uses: "Research only",
        fact: "Francium is extremely rare and radioactive with a half-life of only 22 minutes.",
      },
      {
        symbol: "Ra",
        name: "Radium",
        atomicNumber: 88,
        atomicMass: 226,
        category: "alkaline-earth",
        period: 7,
        group: 2,
        electronConfiguration: "[Rn] 7s²",
        meltingPoint: "700°C",
        boilingPoint: "1737°C",
        uses: "Historic luminous paints, cancer treatment",
        fact: "Radium was discovered by Marie Curie and glows in the dark due to radiation.",
      },

      // Actinides (Period 7)
      {
        symbol: "Ac",
        name: "Actinium",
        atomicNumber: 89,
        atomicMass: 227,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 6d¹ 7s²",
        meltingPoint: "1051°C",
        boilingPoint: "3198°C",
        uses: "Neutron sources, cancer treatment",
        fact: "Actinium is radioactive and glows blue-green in the dark.",
      },
      {
        symbol: "Th",
        name: "Thorium",
        atomicNumber: 90,
        atomicMass: 232.04,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 6d² 7s²",
        meltingPoint: "1750°C",
        boilingPoint: "4788°C",
        uses: "Nuclear fuel, gas mantles, alloys",
        fact: "Thorium is a potential clean nuclear fuel and is more abundant than uranium.",
      },
      {
        symbol: "Pa",
        name: "Protactinium",
        atomicNumber: 91,
        atomicMass: 231.04,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
        meltingPoint: "1572°C",
        boilingPoint: "4000°C",
        uses: "Nuclear research only",
        fact: "Protactinium is extremely rare and was one of the last naturally occurring elements discovered.",
      },
      {
        symbol: "U",
        name: "Uranium",
        atomicNumber: 92,
        atomicMass: 238.03,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
        meltingPoint: "1135°C",
        boilingPoint: "4131°C",
        uses: "Nuclear power, weapons, dating",
        fact: "Uranium powers nuclear reactors and was used to date the age of Earth.",
      },
      {
        symbol: "Np",
        name: "Neptunium",
        atomicNumber: 93,
        atomicMass: 237,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
        meltingPoint: "644°C",
        boilingPoint: "4000°C",
        uses: "Nuclear research, detectors",
        fact: "Neptunium was the first artificially produced transuranium element.",
      },
      {
        symbol: "Pu",
        name: "Plutonium",
        atomicNumber: 94,
        atomicMass: 244,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f⁶ 7s²",
        meltingPoint: "640°C",
        boilingPoint: "3228°C",
        uses: "Nuclear weapons, space missions, power",
        fact: "Plutonium was used in the first nuclear weapons and powers deep space missions.",
      },
      {
        symbol: "Am",
        name: "Americium",
        atomicNumber: 95,
        atomicMass: 243,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f⁷ 7s²",
        meltingPoint: "1176°C",
        boilingPoint: "2607°C",
        uses: "Smoke detectors, neutron sources",
        fact: "Americium is found in household smoke detectors and was named after America.",
      },
      {
        symbol: "Cm",
        name: "Curium",
        atomicNumber: 96,
        atomicMass: 247,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
        meltingPoint: "1345°C",
        boilingPoint: "3110°C",
        uses: "Space missions, research",
        fact: "Curium was named after Marie and Pierre Curie and glows purple in the dark.",
      },
      {
        symbol: "Bk",
        name: "Berkelium",
        atomicNumber: 97,
        atomicMass: 247,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f⁹ 7s²",
        meltingPoint: "986°C",
        boilingPoint: "2627°C",
        uses: "Scientific research only",
        fact: "Berkelium was named after Berkeley, California, where it was first synthesized.",
      },
      {
        symbol: "Cf",
        name: "Californium",
        atomicNumber: 98,
        atomicMass: 251,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f¹⁰ 7s²",
        meltingPoint: "900°C",
        boilingPoint: "1743°C",
        uses: "Neutron sources, cancer treatment",
        fact: "Californium is extremely expensive and used to start nuclear reactors.",
      },
      {
        symbol: "Es",
        name: "Einsteinium",
        atomicNumber: 99,
        atomicMass: 252,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f¹¹ 7s²",
        meltingPoint: "860°C",
        boilingPoint: "1130°C",
        uses: "Scientific research only",
        fact: "Einsteinium was named after Albert Einstein and first discovered in nuclear bomb debris.",
      },
      {
        symbol: "Fm",
        name: "Fermium",
        atomicNumber: 100,
        atomicMass: 257,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f¹² 7s²",
        meltingPoint: "1527°C",
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Fermium was named after Enrico Fermi and has no practical applications due to its short half-life.",
      },
      {
        symbol: "Md",
        name: "Mendelevium",
        atomicNumber: 101,
        atomicMass: 258,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f¹³ 7s²",
        meltingPoint: "827°C",
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Mendelevium was named after Dmitri Mendeleev, creator of the periodic table.",
      },
      {
        symbol: "No",
        name: "Nobelium",
        atomicNumber: 102,
        atomicMass: 259,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f¹⁴ 7s²",
        meltingPoint: "827°C",
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Nobelium was named after Alfred Nobel and exists for only seconds.",
      },
      {
        symbol: "Lr",
        name: "Lawrencium",
        atomicNumber: 103,
        atomicMass: 266,
        category: "actinide",
        period: 7,
        group: null,
        electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹",
        meltingPoint: "1627°C",
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Lawrencium was named after Ernest Lawrence, inventor of the cyclotron.",
      },

      // Super-heavy elements (Period 7)
      {
        symbol: "Rf",
        name: "Rutherfordium",
        atomicNumber: 104,
        atomicMass: 267,
        category: "transition-metal",
        period: 7,
        group: 4,
        electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Rutherfordium was named after Ernest Rutherford and is highly radioactive.",
      },
      {
        symbol: "Db",
        name: "Dubnium",
        atomicNumber: 105,
        atomicMass: 268,
        category: "transition-metal",
        period: 7,
        group: 5,
        electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Dubnium was named after Dubna, Russia, where it was synthesized.",
      },
      {
        symbol: "Sg",
        name: "Seaborgium",
        atomicNumber: 106,
        atomicMass: 269,
        category: "transition-metal",
        period: 7,
        group: 6,
        electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Seaborgium was named after Glenn T. Seaborg, who discovered many transuranium elements.",
      },
      {
        symbol: "Bh",
        name: "Bohrium",
        atomicNumber: 107,
        atomicMass: 270,
        category: "transition-metal",
        period: 7,
        group: 7,
        electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Bohrium was named after Niels Bohr and has a half-life of about 61 seconds.",
      },
      {
        symbol: "Hs",
        name: "Hassium",
        atomicNumber: 108,
        atomicMass: 277,
        category: "transition-metal",
        period: 7,
        group: 8,
        electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Hassium was named after the German state of Hesse and is extremely short-lived.",
      },
      {
        symbol: "Mt",
        name: "Meitnerium",
        atomicNumber: 109,
        atomicMass: 278,
        category: "transition-metal",
        period: 7,
        group: 9,
        electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Meitnerium was named after Lise Meitner, who helped discover nuclear fission.",
      },
      {
        symbol: "Ds",
        name: "Darmstadtium",
        atomicNumber: 110,
        atomicMass: 281,
        category: "transition-metal",
        period: 7,
        group: 10,
        electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Darmstadtium was named after Darmstadt, Germany, where it was first created.",
      },
      {
        symbol: "Rg",
        name: "Roentgenium",
        atomicNumber: 111,
        atomicMass: 282,
        category: "transition-metal",
        period: 7,
        group: 11,
        electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Roentgenium was named after Wilhelm Röntgen, discoverer of X-rays.",
      },
      {
        symbol: "Cn",
        name: "Copernicium",
        atomicNumber: 112,
        atomicMass: 285,
        category: "transition-metal",
        period: 7,
        group: 12,
        electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Copernicium was named after Nicolaus Copernicus and may be liquid at room temperature.",
      },
      {
        symbol: "Nh",
        name: "Nihonium",
        atomicNumber: 113,
        atomicMass: 286,
        category: "post-transition",
        period: 7,
        group: 13,
        electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Nihonium was named after Japan (Nihon) and was the first element discovered in Asia.",
      },
      {
        symbol: "Fl",
        name: "Flerovium",
        atomicNumber: 114,
        atomicMass: 289,
        category: "post-transition",
        period: 7,
        group: 14,
        electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Flerovium was named after Georgy Flyorov and may behave like a noble gas.",
      },
      {
        symbol: "Mc",
        name: "Moscovium",
        atomicNumber: 115,
        atomicMass: 290,
        category: "post-transition",
        period: 7,
        group: 15,
        electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Moscovium was named after Moscow and is predicted to be metallic.",
      },
      {
        symbol: "Lv",
        name: "Livermorium",
        atomicNumber: 116,
        atomicMass: 293,
        category: "post-transition",
        period: 7,
        group: 16,
        electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Livermorium was named after Lawrence Livermore National Laboratory.",
      },
      {
        symbol: "Ts",
        name: "Tennessine",
        atomicNumber: 117,
        atomicMass: 294,
        category: "halogen",
        period: 7,
        group: 17,
        electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Tennessine was named after Tennessee and may not behave like other halogens.",
      },
      {
        symbol: "Og",
        name: "Oganesson",
        atomicNumber: 118,
        atomicMass: 294,
        category: "noble-gas",
        period: 7,
        group: 18,
        electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
        meltingPoint: null,
        boilingPoint: null,
        uses: "Scientific research only",
        fact: "Oganesson was named after Yuri Oganessian and may actually be a solid, not a gas.",
      },
    ];

    console.log(`Initializing ${elementData.length} elements...`);
    for (const element of elementData) {
      await this.createElement(element);
    }
    console.log(`Initialized ${this.elements.size} elements successfully`);

    // Initialize reactions
    const reactionData = [
      {
        reactants: '["H","O"]',
        product: "H₂O",
        productName: "Water",
        description: "Water is the most important compound for life on Earth.",
        uses: "Drinking, cooking, cleaning, industrial processes, and supporting all life forms.",
        facts:
          "Water covers about 71% of Earth's surface and the human body is about 60% water.",
      },
      {
        reactants: '["Na","Cl"]',
        product: "NaCl",
        productName: "Sodium Chloride",
        description: "Common table salt, essential for human nutrition.",
        uses: "Food seasoning, food preservation, de-icing roads, and industrial chemical production.",
        facts:
          'Salt was once so valuable it was used as currency, giving us the word "salary".',
      },
      {
        reactants: '["C","O"]',
        product: "CO₂",
        productName: "Carbon Dioxide",
        description: "A greenhouse gas essential for plant photosynthesis.",
        uses: "Carbonated beverages, fire extinguishers, dry ice, and photosynthesis.",
        facts:
          "CO₂ is what makes bread rise and is used by plants to make oxygen.",
      },
      {
        reactants: '["H","Cl"]',
        product: "HCl",
        productName: "Hydrochloric Acid",
        description:
          "A strong acid used in industry and naturally found in stomach acid.",
        uses: "Steel production, food processing, swimming pool maintenance, and digestion.",
        facts:
          "Your stomach produces about 2-3 liters of hydrochloric acid daily to digest food.",
      },
      {
        reactants: '["Ca","C","O"]',
        product: "CaCO₃",
        productName: "Calcium Carbonate",
        description: "The main component of limestone, marble, and seashells.",
        uses: "Construction materials, paper production, toothpaste, and antacids.",
        facts:
          "Calcium carbonate is what makes eggshells strong and is used in chalk.",
      },
      {
        reactants: '["Fe","O"]',
        product: "Fe₂O₃",
        productName: "Iron Oxide (Rust)",
        description: "The common rust that forms when iron reacts with oxygen.",
        uses: "Pigments, polishing compounds, magnetic storage media.",
        facts:
          "Rust is what gives Mars its red color - the planet is covered in iron oxide.",
      },
      {
        reactants: '["Cu","O"]',
        product: "CuO",
        productName: "Copper Oxide",
        description: "A black compound formed when copper is heated in air.",
        uses: "Catalysts, ceramics, batteries, and semiconductors.",
        facts:
          "Copper oxide gives the green patina color to old copper statues like the Statue of Liberty.",
      },
    ];

    for (const reaction of reactionData) {
      await this.createReaction(reaction);
    }
  }

  async getUser(id: number): Promise<User | undefined> {
    return this.users.get(id);
  }

  async getUserByUsername(username: string): Promise<User | undefined> {
    return Array.from(this.users.values()).find(
      (user) => user.username === username
    );
  }

  async createUser(insertUser: InsertUser): Promise<User> {
    const id = this.currentUserId++;
    const user: User = { ...insertUser, id };
    this.users.set(id, user);
    return user;
  }

  async getAllElements(): Promise<Element[]> {
    return Array.from(this.elements.values()).sort(
      (a, b) => a.atomicNumber - b.atomicNumber
    );
  }

  async getElementById(id: number): Promise<Element | undefined> {
    return this.elements.get(id);
  }

  async getElementBySymbol(symbol: string): Promise<Element | undefined> {
    return Array.from(this.elements.values()).find(
      (element) => element.symbol === symbol
    );
  }

  async createElement(insertElement: InsertElement): Promise<Element> {
    const id = this.currentElementId++;
    const element: Element = {
      ...insertElement,
      id,
      group: insertElement.group ?? null,
      meltingPoint: insertElement.meltingPoint ?? null,
      boilingPoint: insertElement.boilingPoint ?? null,
      uses: insertElement.uses ?? null,
      fact: insertElement.fact ?? null,
    };
    this.elements.set(id, element);
    return element;
  }

  async getAllReactions(): Promise<Reaction[]> {
    return Array.from(this.reactions.values());
  }

  async getReactionByReactants(
    reactants: string[]
  ): Promise<Reaction | undefined> {
    const sortedReactants = reactants.sort();
    return Array.from(this.reactions.values()).find((reaction) => {
      const reactionReactants = JSON.parse(reaction.reactants).sort();
      return (
        JSON.stringify(reactionReactants) === JSON.stringify(sortedReactants)
      );
    });
  }

  async createReaction(insertReaction: InsertReaction): Promise<Reaction> {
    const id = this.currentReactionId++;
    const reaction: Reaction = { ...insertReaction, id };
    this.reactions.set(id, reaction);
    return reaction;
  }
}

export const storage = new MemStorage();
